#! /bin/bash
#
# weekday 1.1.0, 2022-11-13
#
# Get the weekday of an arbitrary date with the help of ncal and grep.
#
# Bernd Storck, https://www.facebook.com/BStLinux/
#

# Static Values:
PROG_NAME="Weekday Determiner"
ORIGINAL_SCRIPT_NAME="weekday"
CURRENT_SCRIPT_NAME="${0##*/}"
#TITLE="$CURRENT_SCRIPT_NAME"
PROG_VERSION="1.1.0"

if [ "${LANG::2}" == "de" ]; then
  UI_LANG="Deutsch"
else
  UI_LANG="English"
fi

TMP_FILE="/tmp/weekday_of_birth"

if [ "$UI_LANG" == "Deutsch" ]; then

  DAY_IN="$(   cut -d. -f1 <<< "$1" )"
  MONTH_IN="$( cut -d. -f2 <<< "$1" )"  
  YEAR="$(  cut -d. -f3 <<< "$1" )"

else  # Parses the input format for non german users.

  YEAR="$(   cut -d'-' -f1 <<< "$1" )"
  MONTH_IN="$( cut -d'-' -f2 <<< "$1" )"  
  DAY_IN="$(  cut -d'-' -f3 <<< "$1" )"

fi

DAY=$(echo "$DAY_IN"   | awk ' { printf ("%02d\n", $1) }')
MONTH=$(echo "$MONTH_IN" | awk ' { printf ("%02d\n", $1) }')

declare tage=( [2]=Montag 
               [3]=Dienstag 
               [4]=Mittwoch 
               [5]=Donnerstag 
               [6]=Freitag 
               [7]=Samstag 
               [8]=Sonntag 
             )

declare days=( [2]=Sunday 
               [3]=Monday 
               [4]=Tuesday 
               [5]=Wednesday 
               [6]=Thursday 
               [7]=Friday 
               [8]=Saturday
             )

# echo "'$DAY' (Input was: $DAY_IN)" "'$MONTH' (Input was: $MONTH_IN)" "'$YEAR'"
# echo "${YEAR}-${MONTH}-${DAY} $MONTH $YEAR" > "$TMP_FILE"
# echo 

function hilfe_seite {
# Displays program purpose and usage help.

echo -e "\n \e[1;33m$PROG_NAME\e[0m ($PROG_VERSION)\n"

echo -e " Das Programm ermittelt auf welchen Wochentag ein Datum fällt.

 AUFRUFBEISPIEL:

  $CURRENT_SCRIPT_NAME 6.2.2024

 ZULÄSSIGE PARAMETER:

  --help|-h|--hilf  Diese Hilfe anzeigen
"
}

function help_page {
# English help

echo -e " The program determines on which day of the week a date falls.

 EXAMPLE CALL:

  $CURRENT_SCRIPT_NAME 2012-08-31

 POSSIBLE PARAMETERS:

  --help|-h|--hilf  Show this help
"
}

function bottom_line {
  if [ "$UI_LANG" == "Deutsch" ]; then
    echo -e "\nDer $1 war/ist ein \033[0;91m${2}\e[0m.\n"
  else
    echo -e "\n$1 was/is a \033[0;91m${2}\e[0m.\n"
  fi
}


### main ###################
case "$1" in
  --hilf|--hilfe|-hilf|-hilfe)  # Calls German help regardless of system settings for language.
    hilfe_seite
    exit 0
    ;;
  --help|-h|-help|-\?|\?)
    if [ "$UI_LANG" == "Deutsch" ]; then
      hilfe_seite
    else
      help_page
    fi
    exit 0
    ;;
esac

ncal -H "${YEAR}-${MONTH}-${DAY}" "$MONTH" "$YEAR" > "$TMP_FILE"

read line < "$TMP_FILE"
echo -e "\n\033[1;37m${line^^}\033[0m"

while read line
do
  (( counter++ ))
  if [ $counter -gt 1 ]; then
    if ! grep --quiet -w "$DAY_IN" <<< "$line"; then
      echo "$line"
    else
      grep --color=always -w "$DAY_IN" <<< "$line"
      [ "$UI_LANG" == "Deutsch" ] && weekday="${tage[$counter]}" || weekday="${days[$counter]}"
    fi
  fi
done < "$TMP_FILE"

bottom_line "$1" "$weekday"

rm -rf "$TMP_FILE"
exit 0
